#!/usr/bin/env python3
"""Tiny client: tell the winswitch daemon to open/advance. Usage: winswitch-send [next|prev]"""
import socket, sys, os
sock = os.path.join(os.environ.get("XDG_RUNTIME_DIR", "/tmp"), "winswitch.sock")
cmd = sys.argv[1] if len(sys.argv) > 1 else "next"
try:
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(1)
    s.connect(sock)
    s.sendall((cmd + "\n").encode())
    s.close()
except Exception:
    pass
